api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/config/api_platform/resources'

    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        xml: [ 'application/xml', 'text/xml' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
        csv: [ 'text/csv' ]

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    enable_swagger_ui: false
    title: Symfony Test
    show_webby: false
