version: '3.5'

services:
  application:
    container_name: application
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ports:
      - '1000:8000'
    networks:
      - application-network

  symfony-db:
    container_name: symfony-db
    image: mysql:8.0
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-db-data:/var/lib/mysql
    networks:
      - application-network

volumes:
  symfony-db-data:

networks:
  application-network: